PREP(updateCautionsList);
PREP(clearCautionsList);
PREP(perSecond);
PREP(registerCautionAdvisory);
PREP(removeCautionAdvisory);
PREP(setup);
PREP(updateAdvisories);
PREP(updateCautionPanel);
PREP(updateCautions);