// SALUTE
#define SALUTE_IDs [0,1,2,3,4,5,6,41,7,8,9,10,11,12,13]
#define SALUTE_ICON ["INFANTRY","MECHANISED INFANTRY","MOTORISED INFANTRY","ARMOR","ROTARY WING","FIXED WING","UNKNOWN","NAVAL","INFANTRY","MACHINEGUN","ANTI-TANK","STATIC MG","STATIC AT","MORTAR","ANTI-AIR"]

// MEDIC
#define MEDIC_IDs [20,21,22,23]
#define MEDIC_ICON ["Casualty","CCP","BAS","MCI"]

// OTHER
#define OTHER_IDs [30,31,32,34,35,36,37,38,39,40]
#define OTHER_ICON ["HQ","LZ","LRP","RlyP","EP","SP","CKP","RP","AA","AO"]
