// Framework
PREP(perFrame);
PREP(perSecond);
PREP(setup);
PREP(shutDown);

PREP(fireWeapon);
PREP(nextWeapon);
PREP(handleKeyInputs);
PREP(handleSlew);
PREP(initVars);
PREP(keyFLIRSlewToHMD);
PREP(keyVisionMode);
PREP(keyZoom);
PREP(mfdNav);
PREP(mfdWaypoint);
PREP(pipStart);
PREP(pipStop);
PREP(scriptedCamera);
PREP(setFOV);
PREP(setIsPipHidden);
PREP(setStabilization);
PREP(setVisionMode);
PREP(syncAnimation);
PREP(syncPilotCamera);
PREP(toggleLaser);
PREP(updateCamera);
PREP(syncPilots);
PREP(updateUIValues);
