#!/usr/bin/env python3
"""
pbo_compare.py - manifest and compare two folders of PBOs (Phase 3 · WP0).

Proves that two builds of the same commit ship the same content, while
tolerating the differences two different packers are *allowed* to produce.
Built for the scons -> HEMTT migration: every difference is classified as
EXPECTED (a known, harmless packer difference) or UNEXPECTED (a real content
difference), and the exit code follows the UNEXPECTED count.

    python tools/pbo_compare.py manifest <dir> [--json out.json]
    python tools/pbo_compare.py compare <dirA> <dirB> [--json out.json] [--verbose]

PBOs are matched across the two folders by their `prefix` header property
(case-insensitive), not by filename - so a renamed output (hct_h60_uh60_mfd.pbo
vs hct_h60_mfd.pbo) still pairs up. Filename-only matching is the fallback for
PBOs without a prefix property.

EXPECTED difference classes (everything else is UNEXPECTED):
  header-prop-added      `hemtt` / `git` / `author` header properties only one side writes
  prefix-case            `prefix` property differs in letter case only
  source-config-shipped  config.cpp packed beside config.bin by Addon Builder only
  stringtable-binarized  stringtable.xml (Addon Builder) vs stringtable.bin (HEMTT)
  rapified-bytes         both sides are raP (config.bin, rapified rvmat/bin) but
                         the bytes differ - rapifiers serialise differently; the
                         VALUES are proven separately with tools/config_dump
  rapified-vs-text       one side ships a text .rvmat/.ext/.sqm/.bisurf, the
                         other the raP form of it
  bytecode-added         *.sqfc only on one side (HEMTT compiles SQF)
  texheaders-cache       texHeaders.bin generated by each packer for itself (presence or bytes)
  timestamp              per-entry timestamps are never compared (counted only)
  entry-order            same entries, different order in the header

Everything is stdlib. Compressed entries ("Cprs") are hashed as stored and
flagged, since neither packer compresses by default.
"""

import argparse
import hashlib
import json
import os
import struct
import sys

RAP_MAGIC = b"\x00raP"
TEXT_RAPIFIABLE = {".rvmat", ".ext", ".sqm", ".bikb", ".bisurf", ".cpp"}
PACKING_NAMES = {0: "none", 0x56657273: "sreV", 0x43707273: "Cprs", 0x456E6372: "Enco"}


# --- PBO reading -------------------------------------------------------------

def _read_cstr(buf, pos):
    end = buf.index(b"\x00", pos)
    return buf[pos:end], end + 1


def read_pbo(path):
    """Return {'file', 'properties': [(k, v)...], 'entries': [...], 'checksum_ok': bool}.

    Each entry: {'name', 'packing', 'original_size', 'timestamp', 'data_size',
                 'sha1' (of stored bytes), 'rap' (bool: stored bytes start with raP)}.
    """
    with open(path, "rb") as fh:
        buf = fh.read()
    pos = 0
    properties = []
    entries = []
    while True:
        name, pos = _read_cstr(buf, pos)
        packing, orig, _reserved, ts, size = struct.unpack_from("<IIIII", buf, pos)
        pos += 20
        if name == b"" and packing == 0x56657273:
            while True:
                key, pos = _read_cstr(buf, pos)
                if key == b"":
                    break
                val, pos = _read_cstr(buf, pos)
                properties.append((key.decode("utf-8", "replace"), val.decode("utf-8", "replace")))
            continue
        if name == b"":
            break
        entries.append({
            "name": name.decode("utf-8", "replace"),
            "packing": PACKING_NAMES.get(packing, hex(packing)),
            "original_size": orig,
            "timestamp": ts,
            "data_size": size,
        })
    for e in entries:
        data = buf[pos:pos + e["data_size"]]
        pos += e["data_size"]
        e["sha1"] = hashlib.sha1(data).hexdigest()
        e["rap"] = data.startswith(RAP_MAGIC)
    body, trailer = buf[:pos], buf[pos:]
    checksum_ok = len(trailer) == 21 and trailer[0:1] == b"\x00" and trailer[1:] == hashlib.sha1(body).digest()
    return {"file": os.path.basename(path), "properties": properties, "entries": entries, "checksum_ok": checksum_ok}


def manifest_dir(folder):
    out = {}
    for name in sorted(os.listdir(folder)):
        if name.lower().endswith(".pbo"):
            out[name] = read_pbo(os.path.join(folder, name))
    return out


def load_side(arg):
    """A folder of PBOs, or a manifest .json written earlier by this tool."""
    if os.path.isdir(arg):
        return manifest_dir(arg)
    with open(arg, encoding="utf-8") as fh:
        return json.load(fh)


# --- comparison --------------------------------------------------------------

def prop(pbo, key):
    for k, v in pbo["properties"]:
        if k.lower() == key:
            return v
    return None


def pair_pbos(a, b):
    """Match PBOs by prefix property (case-insensitive), falling back to filename."""
    def key(pbo, filename):
        p = prop(pbo, "prefix")
        return ("prefix", p.lower().replace("/", "\\")) if p else ("file", filename.lower())
    ka = {key(v, k): k for k, v in a.items()}
    kb = {key(v, k): k for k, v in b.items()}
    pairs = [(ka[k], kb[k]) for k in ka if k in kb]
    only_a = [ka[k] for k in ka if k not in kb]
    only_b = [kb[k] for k in kb if k not in ka]
    return pairs, only_a, only_b


def classify_entry(name, ea, eb):
    """Return (class, detail) for one entry present on both sides with different bytes."""
    ext = os.path.splitext(name)[1].lower()
    if name.lower().endswith("texheaders.bin"):
        return "texheaders-cache", "both sides generate their own"
    if name.lower() == "stringtable.bin":
        # both packers binarize stringtable.xml, with different serialisers
        return "stringtable-binarized", f"{ea['data_size']} vs {eb['data_size']} bytes"
    if ea["rap"] and eb["rap"]:
        return "rapified-bytes", f"{ea['data_size']} vs {eb['data_size']} bytes"
    if (ea["rap"] != eb["rap"]) and (ext in TEXT_RAPIFIABLE or ext == ".bin"):
        side = "A" if ea["rap"] else "B"
        return "rapified-vs-text", f"raP on side {side} only"
    return "UNEXPECTED", f"sha1 {ea['sha1'][:8]} vs {eb['sha1'][:8]}, {ea['data_size']} vs {eb['data_size']} bytes"


def classify_missing(name, side):
    low = name.lower()
    if low.endswith(".sqfc"):
        return "bytecode-added", f"only on side {side}"
    if low.endswith("texheaders.bin"):
        return "texheaders-cache", f"only on side {side}"
    if low == "config.cpp":
        # Addon Builder packs the source config.cpp beside config.bin; HEMTT ships only config.bin
        return "source-config-shipped", f"only on side {side}"
    if low in ("stringtable.xml", "stringtable.bin"):
        # HEMTT binarizes stringtables (stringtable.xml -> stringtable.bin)
        return "stringtable-binarized", f"only on side {side}"
    return "UNEXPECTED", f"only on side {side}"


def compare_pbo(pa, pb):
    findings = []  # (class, what, detail)
    # header properties
    propsa = {k.lower(): v for k, v in pa["properties"]}
    propsb = {k.lower(): v for k, v in pb["properties"]}
    for k in sorted(set(propsa) | set(propsb)):
        va, vb = propsa.get(k), propsb.get(k)
        if va == vb:
            continue
        if va is None or vb is None:
            cls = "header-prop-added" if k in ("hemtt", "git", "author") else "UNEXPECTED"
            findings.append((cls, f"property {k}", f"A={va!r} B={vb!r}"))
        elif k == "prefix" and va.lower().replace("/", "\\") == vb.lower().replace("/", "\\"):
            findings.append(("prefix-case", "property prefix", f"A={va!r} B={vb!r}"))
        else:
            findings.append(("UNEXPECTED", f"property {k}", f"A={va!r} B={vb!r}"))
    if not pa["checksum_ok"]:
        findings.append(("UNEXPECTED", "A trailing checksum", "invalid"))
    if not pb["checksum_ok"]:
        findings.append(("UNEXPECTED", "B trailing checksum", "invalid"))
    # entries (case-insensitive names: Arma does not care, HEMTT may lower-case)
    ea = {e["name"].lower().replace("/", "\\"): e for e in pa["entries"]}
    eb = {e["name"].lower().replace("/", "\\"): e for e in pb["entries"]}
    for name in sorted(set(ea) | set(eb)):
        a, b = ea.get(name), eb.get(name)
        if a is None:
            findings.append(classify_missing(name, "B") + (name,))
            continue
        if b is None:
            findings.append(classify_missing(name, "A") + (name,))
            continue
        if a["packing"] != "none" or b["packing"] != "none":
            findings.append(("UNEXPECTED", name, f"packing A={a['packing']} B={b['packing']}"))
        if a["sha1"] != b["sha1"]:
            cls, detail = classify_entry(name, a, b)
            findings.append((cls, name, detail))
    # fix tuple order for the missing-entry findings: (class, what, detail)
    findings = [(f[0], f[2], f[1]) if len(f) == 3 and f[1].startswith("only on side") else f for f in findings]
    names_a = [e["name"].lower() for e in pa["entries"]]
    names_b = [e["name"].lower() for e in pb["entries"]]
    common = [n for n in names_a if n in set(names_b)]
    common_b = [n for n in names_b if n in set(names_a)]
    if common != common_b:
        findings.append(("entry-order", "header entry order", "same files, different order"))
    ts_diff = sum(1 for n in set(ea) & set(eb) if ea[n]["timestamp"] != eb[n]["timestamp"])
    if ts_diff:
        findings.append(("timestamp", f"{ts_diff} entries", "timestamps differ (never compared)"))
    return findings


def run_compare(a, b, verbose):
    pairs, only_a, only_b = pair_pbos(a, b)
    report = {"pairs": [], "only_a": only_a, "only_b": only_b, "unexpected": 0, "by_class": {}}
    for fa, fb in sorted(pairs):
        findings = compare_pbo(a[fa], b[fb])
        for cls, _, _ in findings:
            report["by_class"][cls] = report["by_class"].get(cls, 0) + 1
            if cls == "UNEXPECTED":
                report["unexpected"] += 1
        report["pairs"].append({"a": fa, "b": fb, "entries_a": len(a[fa]["entries"]),
                                "entries_b": len(b[fb]["entries"]), "findings": findings})
    report["unexpected"] += len(only_a) + len(only_b)
    return report


def print_report(report, verbose):
    for p in report["pairs"]:
        unexpected = [f for f in p["findings"] if f[0] == "UNEXPECTED"]
        expected = [f for f in p["findings"] if f[0] != "UNEXPECTED"]
        status = "FAIL" if unexpected else "ok  "
        name = p["a"] if p["a"].lower() == p["b"].lower() else f"{p['a']} <-> {p['b']}"
        summary = ", ".join(f"{cls}x{n}" for cls, n in sorted(
            {c: sum(1 for f in expected if f[0] == c) for c in {f[0] for f in expected}}.items()))
        print(f"{status} {name}  ({p['entries_a']}/{p['entries_b']} entries)  {summary}")
        for cls, what, detail in unexpected:
            print(f"       UNEXPECTED  {what}: {detail}")
        if verbose:
            for cls, what, detail in expected:
                print(f"       {cls:<18} {what}: {detail}")
    for f in report["only_a"]:
        print(f"FAIL {f}  only in A")
    for f in report["only_b"]:
        print(f"FAIL {f}  only in B")
    print()
    print(f"{len(report['pairs'])} PBO pairs, {len(report['only_a'])} only in A, {len(report['only_b'])} only in B")
    print("difference classes: " + (", ".join(f"{k}={v}" for k, v in sorted(report["by_class"].items())) or "none"))
    print(f"UNEXPECTED differences: {report['unexpected']}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    m = sub.add_parser("manifest", help="list every PBO's header properties and entries")
    m.add_argument("folder")
    m.add_argument("--json", help="write the manifest here (reusable as a compare side)")
    c = sub.add_parser("compare", help="compare two folders (or saved manifests) of PBOs")
    c.add_argument("a")
    c.add_argument("b")
    c.add_argument("--json", help="write the full report here")
    c.add_argument("--verbose", action="store_true", help="also list the EXPECTED differences")
    args = ap.parse_args()

    if args.cmd == "manifest":
        man = manifest_dir(args.folder)
        for name, pbo in man.items():
            props = " ".join(f"{k}={v}" for k, v in pbo["properties"])
            flag = "" if pbo["checksum_ok"] else "  CHECKSUM INVALID"
            print(f"{name}: {len(pbo['entries'])} entries, {props}{flag}")
        if args.json:
            with open(args.json, "w", encoding="utf-8") as fh:
                json.dump(man, fh, indent=1)
            print(f"manifest written to {args.json}")
        return 0

    a, b = load_side(args.a), load_side(args.b)
    report = run_compare(a, b, args.verbose)
    print_report(report, args.verbose)
    if args.json:
        with open(args.json, "w", encoding="utf-8") as fh:
            json.dump(report, fh, indent=1)
        print(f"report written to {args.json}")
    return 1 if report["unexpected"] else 0


if __name__ == "__main__":
    sys.exit(main())
