name: Steam_Upload/Dev

on:
  push:
    branches:
    - main

jobs:
  build_addon:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set VERSION env
      run: echo VERSION=${GITHUB_REF:11} >> $GITHUB_ENV
    - name: Build addon with HEMTT
      uses: arma-actions/hemtt@master
      with:
        command: 'build --release'
    # Upload to Steam Workshop
    - name: Extract mod.zip
      run: cd releases && sudo unzip hatchet.zip
    - uses: arma-actions/workshop-upload@v1
      with:
        appId: '107410'    # default
        itemId: '2403978406' # Id of item to update
        contentPath: 'releases/@hatchet'
        changelog: 'Content of change notes'
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
