class type_wrapper {
    color[] = common_blue;
    TEXT_MID_MID(JVMF_MESSAGE_TYPE,0.5,JVMF_TOP_MARGIN - (JVMF_LINE_HEIGHT * 1),"FREETEXT MESSAGE")
    TEXT_LEFT_MID(JVMF_TITLE_LABEL,JVMF_LEFT_ALIGN,JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 0),"MSG TITLE")
};

TEXT_LEFT_MID_USERTEXT(JVMF_TITLE,JVMF_LEFT_ALIGN + 0.18,JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 0),30)
TEXT_LEFT_MID_USERTEXT(JVMF_LINE1,JVMF_LEFT_ALIGN,JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 1),31)
TEXT_LEFT_MID_USERTEXT(JVMF_LINE2,JVMF_LEFT_ALIGN,JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 2),32)
TEXT_LEFT_MID_USERTEXT(JVMF_LINE3,JVMF_LEFT_ALIGN,JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 3),33)
TEXT_LEFT_MID_USERTEXT(JVMF_LINE4,JVMF_LEFT_ALIGN,JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 4),34)
TEXT_LEFT_MID_USERTEXT(JVMF_LINE5,JVMF_LEFT_ALIGN,JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 5),35)
TEXT_LEFT_MID_USERTEXT(JVMF_LINE6,JVMF_LEFT_ALIGN,JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 6),36)
TEXT_LEFT_MID_USERTEXT(JVMF_LINE7,JVMF_LEFT_ALIGN,JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 7),37)
TEXT_LEFT_MID_USERTEXT(JVMF_LINE8,JVMF_LEFT_ALIGN,JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 8),38)
TEXT_LEFT_MID_USERTEXT(JVMF_LINE9,JVMF_LEFT_ALIGN,JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 9),39)
TEXT_LEFT_MID_USERTEXT(JVMF_LINE10,JVMF_LEFT_ALIGN,JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 10),40)
class reply_wrapper {
    color[] = common_blue;
    TEXT_LEFT_MID(JVMF_REPLY_LABEL,JVMF_LEFT_ALIGN,JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 11),"STATUS")
};
TEXT_LEFT_MID_USERTEXT(JVMF_REPLY,JVMF_LEFT_ALIGN + 0.18,JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 11),41)


#define JVMF_BORDER_MARGIN 0.02
#define JVMF_BOTTOM_MARGIN 0.14
class jvmf_border {
    color[] = common_blue;
    class title_box {
        type="line";
        width = 3;
        points[] = {
            {{JVMF_LEFT_ALIGN - JVMF_BORDER_MARGIN, JVMF_TOP_MARGIN - JVMF_LINE_HEIGHT}, 1},
            {{1 - JVMF_LEFT_ALIGN + JVMF_BORDER_MARGIN, JVMF_TOP_MARGIN - JVMF_LINE_HEIGHT}, 1},
            {{1 - JVMF_LEFT_ALIGN + JVMF_BORDER_MARGIN, JVMF_TOP_MARGIN + JVMF_LINE_HEIGHT}, 1},
            {{JVMF_LEFT_ALIGN - JVMF_BORDER_MARGIN, JVMF_TOP_MARGIN + JVMF_LINE_HEIGHT}, 1},
            {{JVMF_LEFT_ALIGN - JVMF_BORDER_MARGIN, JVMF_TOP_MARGIN - JVMF_LINE_HEIGHT}, 1}
        };
    }; // title_box
    class content_box {
        type="line";
        width = 3;
        points[] = {
            {{1 - JVMF_LEFT_ALIGN + JVMF_BORDER_MARGIN, JVMF_TOP_MARGIN + JVMF_LINE_HEIGHT}, 1},
            {{1 - JVMF_LEFT_ALIGN + JVMF_BORDER_MARGIN, JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 11)}, 1},
            {{JVMF_LEFT_ALIGN - JVMF_BORDER_MARGIN, JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 11)}, 1},
            {{JVMF_LEFT_ALIGN - JVMF_BORDER_MARGIN, JVMF_TOP_MARGIN + JVMF_LINE_HEIGHT}, 1}
        };
    }; // content_box
    class reply_box {
        type="line";
        width = 3;
        points[] = {
            {{1 - JVMF_LEFT_ALIGN + JVMF_BORDER_MARGIN, JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 11)}, 1},
            {{1 - JVMF_LEFT_ALIGN + JVMF_BORDER_MARGIN, JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 12)}, 1},
            {{JVMF_LEFT_ALIGN - JVMF_BORDER_MARGIN, JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 12)}, 1},
            {{JVMF_LEFT_ALIGN - JVMF_BORDER_MARGIN, JVMF_TOP_MARGIN + (JVMF_LINE_HEIGHT * 11)}, 1}
        };
    }; // content_box
}; // jvmf_border
